In [ ]:
# program 2: store building usage data
building_usage = {
    "CSE": 450,
    "MECH": 800
}
print("MECH used:", building_usage["MECH"], "KWh")

MECH used: 800 KWh

In [1]:
# program 1: calculate total weekly energy from a list
daily_Kwh = [400, 850, 400, 350, 500, 600]
total_energy = sum(daily_Kwh)
print("Total Energy Used:", total_energy, "KWh")

Total Energy Used: 3100 KWh

In [7]:
# program 3: A function to calculate electricity cost
def calculate_bill(Kwh, rate_per_unit):
  return Kwh * rate_per_unit

  todays_bill = calculate_bill(400,8)
  print("Today's estimated bill is Rs.", todays_bill)

In [13]:
# program 4: Read a file line by line
with open("Campus_energy.csv", "r") as file:
  for line in file.readlines():
    print(line.strip())

﻿Date,Building,KWh_UsedPeak_Hour_Usage,
05-09-2026,CSE,300,111
06-09-2026,AI&ML,400,121
07-09-2026,CSE,500,131
08-09-2026,ECE,600,141
09-09-2026,CIVIL,700,151
10-09-2026,AI&ML,800,161
11-09-2026,CSE,900,171
12-09-2026,AI&DS,200,181
13-09-2026,MECH,100,191

In [18]:
# import the pandas library
import pandas as pd

# Load the dataset you created
df = pd.read_csv('Campus_energy.csv')

# display the first few rows of the data
print("Here is the raw data:")
display(df.head())

# Group the data to see total usage per building
building_totals = df.groupby('Building')['Kwh_used'].sum()
print(building_totals)

# Generate a statistical summary (average, min, max) of the numeric columns
 print("\nStatistical Summary:")
 display(df.describe())

Here is the raw data:

         Date Building  KWh_UsedPeak_Hour_Usage  Unnamed: 3
0  05-09-2026      CSE                      300         111
1  06-09-2026    AI&ML                      400         121
2  07-09-2026      CSE                      500         131
3  08-09-2026      ECE                      600         141
4  09-09-2026    CIVIL                      700         151

Building
AI&DS     200
AI&ML    1200
CIVIL     700
CSE      1700
ECE       600
MECH      100
Name: KWh_UsedPeak_Hour_Usage, dtype: int64

Statistical Summary:

       KWh_UsedPeak_Hour_Usage  Unnamed: 3
count                 9.000000    9.000000
mean                500.000000  151.000000
std                 273.861279   27.386128
min                 100.000000  111.000000
25%                 300.000000  131.000000
50%                 500.000000  151.000000
75%                 700.000000  171.000000
max                 900.000000  191.000000

In [21]:
# Create the README.md file and write a message inside it
with open("README.md", "w") as file:
  file.write("# Smart Campus Energy Project\n")
  file.write("This repository cotains my Week 1 hands-on Python and pandas assignments.\n")
  file.write("Created by: [Dimpu]")

print("README.md has been successfully created!")

README.md has been successfully created!